### ISSUE TITLE
Porting quarto articles to documenter

### ISSUE THREAD

**Issue by lrnv** [FJRubio67/HazReg.jl#2]
@FJRubio67 Could you share with me the source files of the HazReg.jl-related quarto stuff from https://fjrubio.quarto.pub/ ? I would like to move them to the documentation of the package to use as crude tests for the simplifications in #1

**Comment by FJRubio67** [comment]
@lrnv Of course. Please, find them attached.
[Quarto.zip](https://github.com/FJRubio67/HazReg.jl/files/14623326/Quarto.zip)

**Comment by lrnv** [comment]
Let to #3, thanks !
