### ISSUE TITLE
Configure the repo for online docs

### ISSUE THREAD

**Issue by lrnv** [FJRubio67/HazReg.jl#6]
Hey, 

This is something that only you can do to solve the faillure from https://github.com/FJRubio67/HazReg.jl/actions/runs/8308294730/job/22738389978

You have to follow this guide to setup documenter correctly : https://m3g.github.io/JuliaNotes.jl/stable/publish_docs/

In particular, I think you have to use DocumenterTools to generates secret keys and add them to the repo so that the automatic compilation of the documentation can push to github pages. Tell me if that is not clear enough :)

**Comment by FJRubio67** [comment]
@lrnv I have followed the first two steps using the DocumenterTools and generating the SSH key. I am not sure if this solves the issue, so, let me know if I missed something.

**Comment by lrnv** [comment]
But it does not look like this is the problem however... I think we should ask on discourse about the observed error on CI.

**Comment by FJRubio67** [comment]
@lrnv I will have a look as soon as I can, but it will probably have to wait until April.

**Comment by lrnv** [comment]
I asked for help there https://discourse.julialang.org/t/documenter-jl-failling-to-push-im-a-bit-lost/111777

**Comment by lrnv** [comment]
See krastonov answer there, maybe that'll be enough. it's hard to diagnose without ownership ^^

**Comment by FJRubio67** [comment]
@lrnv "Read and write permissions" are now enabled. I am not sure I understand the second part ("proper solution") in the link.

**Comment by lrnv** [comment]
Try to commit something ? E.g. remove that ugly folder under `docs` ?

**Comment by lrnv** [comment]
Here is a guide: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by lrnv** [comment]
Haaaa found it ! It is trying to find the /docs folder while there is none. In your settings, under the `Page` tab on the left, you should put : 

![image](https://github.com/FJRubio67/HazReg.jl/assets/15571061/ed6ee4fd-bd8c-4c9e-8d29-8872da18baa6)

Your's should show `/docs` instead of `/ (root)`: change it to `/ (root)`.

**Comment by lrnv** [comment]
Looks like here : https://github.com/FJRubio67/HazReg.jl/actions/runs/8332140704/job/22800603515#step:4:3 that it is still on "/docs". Can you screen shot this part of your settings for me ?

**Comment by FJRubio67** [comment]
I created a new release to properly trigger the CI. It has now passed all checks. I will check your comments in a minute.

**Comment by lrnv** [comment]
The release was not needed (you'll get `dev` docs without it, but it's enough for the moment). But this comment (put Jekyll on root instead of docs) is necessary for it to work correctly ;)

**Comment by FJRubio67** [comment]
The documentation seems to be working now ... https://fjrubio67.github.io/HazReg.jl/stable/

**Comment by lrnv** [comment]
It worked ! You can see the docs there : https://fjrubio67.github.io/HazReg.jl/ :)

So there you can see your articles that I ported to this syntax -- not very hard to do it's suite similar. These pages will be automatically updated on each commit to master (on the `dev` documentation) and on each release ( on the `stable` documentation). 

From this, we now have graphs and stuff to validate the outputs of the package as we modify it. 

Thanks, now I can get back to the drastic code simplification I had at the begining, while being certain that I do not breaker everything :)
