### ISSUE TITLE
Documentation does not deploy

### ISSUE THREAD

**Issue by lrnv** [FJRubio67/HazReg.jl#8]
Looks like the new docs got compiled and pushed to the `gh-pages` branch correctly, but they were not deployed on the website `/dev/` folder.

I do not know why the page build did not trigger automatically... I'm sorry

**Comment by lrnv** [comment]
This is very weird, there is clearly a configuration issue somewhere but I cannot diagnosis it myself I'm sorry.

**Comment by FJRubio67** [comment]
There seems to be a problem with the compilation of HazReg indeed. I will have a look later. Meanwhile, I think it is safer to revert the merge until we have a stable implementation (or until I have time to understand the new syntax).

**Comment by lrnv** [comment]
As you want, it's your code. This is not a compilation problem but rather a deployment problem of the documentation.

**Comment by FJRubio67** [comment]
Happy to continue with the merge when we sort these issues. Sorry, I have limited time now, and I was hoping things would be smoother, but this seems to require more work on my side than anticipated.
